### ISSUE TITLE
Problème d'affichage de documents dans glpi provoqué par mreporting 

### ISSUE THREAD

**Issue by Gwenall-Photobox** [pluginsGLPI/mreporting#10]
Bonjour, 

J'ai remarqué un probleme d'affichage de documents de type image (jpg et png) dans glpi qui est lié a la présence de mreporting.

Explications: 
En temps normal, sans le plugin mreporting, il est possible d'afficher des documents dans glpi en full screen: (http://server-glpi/front/document.send.php?docid=10), 
mais aussi dans talk: 
![screenshot from 2015-06-27 15 52 21](https://cloud.githubusercontent.com/assets/10615766/8392504/2c715948-1ce5-11e5-985e-9489a4587588.png)

--------------------------------

Apres avoir installé et activé mreporting :
J'obtiens un message d'erreur en full screen.
![screenshot from 2015-06-27 16 22 41](https://cloud.githubusercontent.com/assets/10615766/8392645/cecea170-1ce8-11e5-8a33-65eee8979bd1.png)

et un probleme d'affichage dans talk:
![screenshot from 2015-06-27 16 01 12](https://cloud.githubusercontent.com/assets/10615766/8392543/c44d78b4-1ce5-11e5-96b0-6614fe0c1ed7.png)

-------------------------------

J'ai noté que le fichier "setup.php", dans /var/www/glpi/plugins/mreporting, semble être a l'origine de ce problème.
Quand on supprime ce fichier, l'affichage des documents est de nouveau normal, par contre mreporting ne fonctionne plus.

--------------

Pour faire fonctionner mreporting et l'affichage de documents, j'ai dû commenter des lignes 77 et 78 de mreporting/setup.php

![screenshot from 2015-06-27 16 12 04](https://cloud.githubusercontent.com/assets/10615766/8392582/4dcdbcba-1ce7-11e5-9e40-e807324e9ac7.png)

Cependant je ne sais absolument pas quels sont les impacts possibles dus à cette modification.
En espérant vous avoir donné suffisamment d'information.

GLPI : 0.85.2
mreporting : 0.85+1.0 (RC4)

Merci d'avance,

**Comment by flegastelois** [comment]
Bonjour, 

Pouvez-vous nous indiquer si vous avez des erreurs qui s'affichent en mode debug? (en tant que super-admin vous pouvez activer ce mode dans vos préférences)

Également, il faudrait regarder les fichiers de logs suivants :
- celui de GLPI (glpi/files/_log/php-errors.log)
- celui d'Apache (sous linux, souvent dans : /var/log/apache2/errors.log)

Supprimer le fichier setup de mreporing revient à le désactiver, et si en le désactivant cela fonctionne c'est qu'il doit générer une erreur pour que vos images ne s'affichent plus.

Il faut donc trouver cette erreur :)

Bien à vous, 
François

**Comment by Gwenall-Photobox** [comment]
Bonsoir,
 
Merci de me répondre aussi rapidement :-) 
Ok, je vais essayer de trouver l'erreur en mode débug

Cordialement,
Gwenall

**Comment by neeftarah** [comment]
Bonjour,

Je ne reproduit pas ce bug (GLPI 0.85.4 / Mreporting 0.85+1.0RC4 / Discution 0.85-1.1).

Il est possible que ce bug soit lié à plusieurs critères, version de GLPI, autres plugins présents, etc.

Pouvez-vous me confirmer que vous rencontrer toujours ce problème et, si c'est le cas, pouvez-vous me transmettre la liste de vos plugins et versions ?

Cordialement,
Jérémy

**Comment by Gwenall-Photobox** [comment]
Bonjour, 
J'ai recemment trouvé d'où provenait cette erreur: 
Il y avait un conflit entre le plugin mreporting et le plugin talk
Pour temporairement resoudre ce probleme, j'ai commenté une partie du code de:
glpi/plugins/mreporting/setup.php 
de la ligne 76 a la ligne 89 
soit: 


         /* Show Reports in standart stats page */
         //Commented out [Bug : pictures not displayed in all glpi]
         /*
                 $mreporting_common = new PluginMreportingCommon();
                  $reports = $mreporting_common->getAllReports();

                  if ($reports !== false) {
                     foreach($reports as $report) {
                        foreach($report['functions'] as $func) {
                           $PLUGIN_HOOKS['stats']['mreporting'][$func['min_url_graph']] = $func['title'];
                        }
                     }
                  }
         */


Concernant la version des plugins:
Talks version 0.85-1.1
More Reporting 0.85+1.0

En espérant que ces informations vous seront utiles.

Cordialement,
Gwenall
