### ISSUE TITLE
[9.2] Graphs "Per SLA" - Error: Table 'glpi.glpi_slts' doesn't exist

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/mreporting#122]
>   Error: Table 'glpi.glpi_slts' doesn't exist
  Backtrace :
  plugins/mreporting/inc/helpdeskplus.class.php:813  
  plugins/mreporting/inc/common.class.php:624        PluginMreportingHelpdeskplus->reportHgbarRespectedSlasByTechnician()
  plugins/mreporting/front/graph.php:42              PluginMreportingCommon->showGraph()

**Comment by trasher** [comment]
Fixed in https://github.com/pluginsGLPI/mreporting/pull/124
