### ISSUE TITLE
mreporting 1.4.0  - This version require GLPI 9.2

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/mreporting#131]
**GLPI 9.2 compatible** is not perfect ;)

1.4.0 This version requires GLPi >= 9.2 (not compatible with GLPi 9.1)
would be better again

my version GLPI 9.1.6 Copyright (C) 2015-2017 Teclib' and c

**Comment by Armin83** [comment]
https://i.imgur.com/P7oS8OP.png

**Comment by cedric-anne** [comment]
Hi,

I do not understand what is your problem. Can you explain ?

Regards

**Comment by Armin83** [comment]
The version string or the information to the version (here on github) is not perfekt.

1.4.0 compatible with glpi 9.2. I tought i can use it also with 9.1 but this version did not work with 9.1. 
There were bug fixes or a new features in 1.4.0 so i want to use it.

Imho compatible with glpi means i can use it with other version too.
only for 9.2 would be better

**Comment by trasher** [comment]
Changed
