### ISSUE TITLE
 [9.2.2] issue with mreporting

### ISSUE THREAD

**Issue by ppenin** [pluginsGLPI/mreporting#140]
mreporting 1.4.0 displays a blank page with any item selected with GLPI 9.2.2.
Debug mode shows theses errors 
PHP Notice: Undefined index: default_graphtype in /usr/share/glpi/plugins/mreporting/inc/common.class.php at line 595
PHP Notice: Undefined index: default_graphtype in /usr/share/glpi/plugins/mreporting/inc/common.class.php at line 598
PHP Notice: Undefined variable: graph in /usr/share/glpi/plugins/mreporting/inc/common.class.php at line 640

Fatal error: Uncaught Error: Call to a member function showvstackbar() on null in /usr/share/glpi/plugins/mreporting/inc/common.class.php:640 Stack trace: #0 /usr/share/glpi/plugins/mreporting/inc/dashboard.class.php(191): PluginMreportingCommon->showGraph(Array) #1 /usr/share/glpi/plugins/mreporting/front/dashboard.form.php(48): PluginMreportingDashboard->showDashBoard() #2 /usr/share/glpi/plugins/mreporting/front/dashboard.php(2): require_once('/usr/share/glpi...') #3 {main} thrown in /usr/share/glpi/plugins/mreporting/inc/common.class.php on line 640

**Comment by coderdev21** [comment]
I get the same error.
GLPI 9.2.2
CentOS Linux 7.4.1708
Apache version 2.4.6
MySQL version 5.5.56
PHP version 7.2.3

**Comment by cblourenco** [comment]
Help

GLPI v 9.2.2
mreporting v 1.4.0 

displays a blank page with any item selected with 

PHP Notice: Undefined index: default_graphtype in C:\xampp\htdocs\glpi\plugins\mreporting\inc\common.class.php at line 595
PHP Notice: Undefined index: default_graphtype in C:\xampp\htdocs\glpi\plugins\mreporting\inc\common.class.php at line 598
PHP Notice: Undefined variable: graph in C:\xampp\htdocs\glpi\plugins\mreporting\inc\common.class.php at line 640

Fatal error: Uncaught Error: Call to a member function showhbar() on null in C:\xampp\htdocs\glpi\plugins\mreporting\inc\common.class.php:640 Stack trace: #0 C:\xampp\htdocs\glpi\plugins\mreporting\front\graph.php(42): PluginMreportingCommon->showGraph(Array) #1 {main} thrown in C:\xampp\htdocs\glpi\plugins\mreporting\inc\common.class.php on line 640

**Comment by pxlcore** [comment]
Same error here after Update to GLPI 9.2.2.

PHP Fatal erro: Call to a member function showhgbar() on null in /home/helpdesk/htdocs/plugins/mreporting/inc/common.class.php on line 640

**Comment by willijm** [comment]
My error 

PHP Notice: Undefined index: default_graphtype in /var/www/glpi/plugins/mreporting/inc/common.class.php at line 595
PHP Notice: Undefined index: default_graphtype in /var/www/glpi/plugins/mreporting/inc/common.class.php at line 598
PHP Notice: Undefined variable: graph in /var/www/glpi/plugins/mreporting/inc/common.class.php at line 640

Fatal error: Uncaught Error: Call to a member function showpie() on null in /var/www/glpi/plugins/mreporting/inc/common.class.php:640 Stack trace: #0 /var/www/glpi/plugins/mreporting/front/graph.php(42): PluginMreportingCommon->showGraph(Array) #1 {main} thrown in /var/www/glpi/plugins/mreporting/inc/common.class.php on line 640

**Comment by Ludwig33** [comment]
Same Issue for me.

Is mreporting project dead ?

PHP Notice: Undefined index: default_graphtype in /var/www/glpi/plugins/mreporting/inc/common.class.php at line 595
PHP Notice: Undefined index: default_graphtype in /var/www/glpi/plugins/mreporting/inc/common.class.php at line 598
PHP Notice: Undefined variable: graph in /var/www/glpi/plugins/mreporting/inc/common.class.php at line 640

Fatal error: Uncaught Error: Call to a member function showsunburst() on null in /var/www/glpi/plugins/mreporting/inc/common.class.php:640 Stack trace: #0 /var/www/glpi/plugins/mreporting/front/graph.php(42): PluginMreportingCommon->showGraph(Array) #1 {main} thrown in /var/www/glpi/plugins/mreporting/inc/common.class.php on line 640

**Comment by grcmec** [comment]
Hi I have the same issue.
PHP Notice: Undefined index: default_graphtype in C:\xampp\htdocs\glpi-Curso\plugins\mreporting\inc\common.class.php at line 595
PHP Notice: Undefined index: default_graphtype in C:\xampp\htdocs\glpi-Curso\plugins\mreporting\inc\common.class.php at line 598
PHP Notice: Undefined variable: graph in C:\xampp\htdocs\glpi-Curso\plugins\mreporting\inc\common.class.php at line 640

Fatal error: Uncaught Error: Call to a member function showpie() on null in C:\xampp\htdocs\glpi-Curso\plugins\mreporting\inc\common.class.php:640 Stack trace: #0 C:\xampp\htdocs\glpi-Curso\plugins\mreporting\inc\dashboard.class.php(191): PluginMreportingCommon->showGraph(Array) #1 C:\xampp\htdocs\glpi-Curso\plugins\mreporting\ajax\dashboard.php(25): PluginMreportingDashboard->showDashBoard(false) #2 {main} thrown in C:\xampp\htdocs\glpi-Curso\plugins\mreporting\inc\common.class.php on line 640

**Comment by AircraftRu** [comment]
I've it in the log:
```
2018-03-29 17:36:07 Europe/Moscow [7@glpi]
  *** PHP Notice(8): Undefined variable: graph
  Backtrace :
  plugins/mreporting/inc/common.class.php:640        
  plugins/mreporting/inc/dashboard.class.php:191     PluginMreportingCommon->showGraph()
  plugins/mreporting/ajax/dashboard.php:25           PluginMreportingDashboard->showDashBoard()
```

**Comment by vagneraragao** [comment]
You need to go to Setup, Plugin, More Report then change the graphics from GLPI to SVG in each Report like (reportAreaNbTicket)
![img1](https://user-images.githubusercontent.com/22115915/38253844-15d0eb70-372e-11e8-8983-6b1d8d35bc92.png)


![img2](https://user-images.githubusercontent.com/22115915/38253862-1f46beb4-372e-11e8-9f34-38cc6ccea947.png)

**Comment by ppenin** [comment]
Issue is gone after changing default chart format from GLPI to SVG in each report
Many thanx !

**Comment by wellington1993** [comment]
Worked! @vagneraragao Thanks!

**Comment by phep** [comment]
Hi,

Laziness inducted me to simply change the value of the `graphtype` column for all lines in the `glpi_plugin_mreporting_configs` table from GLPI to SVG. It seems to work as well.

**Comment by cedric-anne** [comment]
Fixed by https://github.com/pluginsGLPI/mreporting/pull/149.
