### ISSUE TITLE
i can see any report

### ISSUE THREAD

**Issue by jswytka** [pluginsGLPI/mreporting#142]
I´m using glpi v9.2.2 mreporting 1.4.0... dont works for me.

No errors during installation but i cant see any reports

Help me please

![imagem 3](https://user-images.githubusercontent.com/21204053/38450044-661464ce-39ed-11e8-9279-46a5fce474d9.png)

**Comment by jtoset** [comment]
Me too :-(

**Comment by cp61** [comment]
Me too with v9.2.2

**Comment by kiasys** [comment]
Same problem with GLPI v9.2.2. Any ideas?

**Comment by kiasys** [comment]
Answer there [https://github.com/pluginsGLPI/mreporting/issues/140](https://github.com/pluginsGLPI/mreporting/issues/140)

**Comment by cedric-anne** [comment]
Fixed by https://github.com/pluginsGLPI/mreporting/pull/149.
