### ISSUE TITLE
[glpi 9.2.3 vs 1.4.0] error php notice Undefined index

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/mreporting#146]
Select a report to display : 

No report works

PHP Notice: Undefined index: default_graphtype in /var/www/glpi/plugins/mreporting/inc/common.class.php at line 595
PHP Notice: Undefined index: default_graphtype in /var/www/glpi/plugins/mreporting/inc/common.class.php at line 598
PHP Notice: Undefined variable: graph in /var/www/glpi/plugins/mreporting/inc/common.class.php at line 640

Fatal error: Uncaught Error: Call to a member function showgline() on null in /var/www/glpi/plugins/mreporting/inc/common.class.php:640 Stack trace: #0 /var/www/glpi/plugins/mreporting/inc/dashboard.class.php(191): PluginMreportingCommon->showGraph(Array) #1 /var/www/glpi/plugins/mreporting/front/dashboard.form.php(48): PluginMreportingDashboard->showDashBoard() #2 /var/www/glpi/plugins/mreporting/front/dashboard.php(2): require_once('/var/www/glpi/p...') #3 {main} thrown in /var/www/glpi/plugins/mreporting/inc/common.class.php on line 640

**Comment by Megachip** [comment]
`PHP Notice: Undefined index: right in /usr/share/glpi/plugins/mreporting/inc/profile.class.php at line 228
No access
`

**Comment by cedric-anne** [comment]
Initial issue fixed by https://github.com/pluginsGLPI/mreporting/pull/149.

**Comment by cedric-anne** [comment]
@Armin83 Your issue has been fixed and fix will be included in next release.

@Megachip Your issue seems to be the same as https://github.com/pluginsGLPI/mreporting/issues/28.
