### ISSUE TITLE
empty dashboard and php errors

### ISSUE THREAD

**Issue by lexx015** [pluginsGLPI/mreporting#15]
Hi!
I have been issued with mreporting plugin from GLPI 0.84.x.
Now i'm trying with GLPI 0.90 and the latest version of mreporting plugin and have same error.

This happens with russian interface language. With english all works fine.

php version: PHP 5.6.2-1 
apache version: Apache/2.4.10 (Debian)

php error:
2015-09-04 17:12:59 [6@vmvm]
  *** PHP Notice(8): Undefined index: classname
  Backtrace :
  plugins/mreporting/inc/dashboard.class.php:157
  plugins/mreporting/front/dashboard.form.php:34     PluginMreportingDashboard->showDashBoard()
  plugins/mreporting/front/dashboard.php:3           require_once()

<b>upd:</b> ah, there is no russian translation for this plugin.

**Comment by neeftarah** [comment]
Fixed by your merge request, commit: 4d0b092
Thanks for translations.
I have added mreporting to Transifex. You are already in our translators team, so you can update translation if needed.
