### ISSUE TITLE
Some reports cannot be added to Dashboard

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/mreporting#170]
plugin version 1.5.2 (with GLPI 9.3.1)

Some reports have the same name, not in db but in translation files.
Example in French : "Evolution du nombre de ticket sur la période (par Statut)" is used 3 times.
But in the list displayed to add a report to dashboard, it appears only once ! Because of duplicates on name.
As a consequence, not all reports can be used in dashboard

**Comment by blerohellec** [comment]
Same for the list displayed on top of the dashboard page, titled 'select a report to display' : some report are missing, the duplicates by name

**Comment by cedric-anne** [comment]
Hi,

Could you check if https://github.com/pluginsGLPI/mreporting/pull/173 fixes your issue ?

Regards

**Comment by blerohellec** [comment]
Yes, it's OK. #173 fixes the problem.
