### ISSUE TITLE
Bug icon when enable plugin on glpi 9.4.0

### ISSUE THREAD

**Issue by tguichard25** [pluginsGLPI/mreporting#175]
Hello,

When I enable the plugin, some icon bug.
![image](https://user-images.githubusercontent.com/47602797/52722708-79737180-2fac-11e9-9f41-aad9d70a3fb0.png)
![image](https://user-images.githubusercontent.com/47602797/52722720-8001e900-2fac-11e9-9e17-3765d4fbf44e.png)

**Comment by orthagh** [comment]
In fact, we already fixed the bug.
See https://github.com/pluginsGLPI/mreporting/commit/78a281dde347fc639e802107ae5a40a7e6822df5

By the way we didn't release yet a version of the plugin with the fix.

@cedric-anne Could you check this ?

**Comment by cedric-anne** [comment]
Hi,

The 1.6.0 release was published 2 months ago (for GLPI 9.4 RC). We have to do a new release to include this fix.

Regard

**Comment by cedric-anne** [comment]
Fixed by 78a281dde347fc639e802107ae5a40a7e6822df5.
