### ISSUE TITLE
A 404 error page : front/common.php

### ISSUE THREAD

**Issue by Manu1400** [pluginsGLPI/mreporting#18]
In page plugins/mreporting/front/graph.php?short_classname=Helpdeskplus&f_name=reportGlineBacklogs&gtype=gline the menu have a link to a 404 page : plugins/mreporting/front/common.php

**Comment by neeftarah** [comment]
Salut,

Peut-tu développé un peu ton soucis ?
Le rapport Backlog ici cité semble très bien fonctionner...
- As-tu chargé / rechargé les rapports (Plus de Rapports > Configuration > Initialiser la configuration des graphiques) ?
- As-tu vérifié les droits d'accès et essayer de les recharger ? (Administration > Profils > Plus de rapports) 

`the menu have a link to a 404 page : plugins/mreporting/front/common.php`

Quel menu ?

Quel version de GLPI / Plus de rapports utilise-tu ?

Cordialement,
Jérémy
