### ISSUE TITLE
PHP Warning(2): include_once(): Failed opening '/var/www/html/glpi/plugins/mreporting/vendor/autoload.php'

### ISSUE THREAD

**Issue by abnerrizzi** [pluginsGLPI/mreporting#180]
My first time here and I noticed a lot of errors like these in my log file, someone cloud help me to understand this problem:

```
[2019-07-04 10:42:08] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Warning(2): include_once(): Failed opening '/var/www/html/glpi/plugins/mreporting/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php')
  Backtrace :
  plugins/mreporting/setup.php:53                    
  plugins/mreporting/setup.php:53                    include_once()
  inc/plugin.class.php:316                           include_once()
  inc/plugin.class.php:318                           Plugin->{closure}()
  inc/plugin.class.php:287                           Plugin->checkPluginState()
  inc/plugin.class.php:123                           Plugin->checkStates()
  inc/includes.php:99                                Plugin->init()
  ajax/ticketassigninformation.php:36                include()
  {"user":"13@u18-glpi","mem_usage":"0.000\", 1.77Mio)"} 

```

PS.: my English is a little rusty

**Comment by cedric-anne** [comment]
Hi,

You should either download the build archive (the .tar.bz2 file), either install dependencies using composer.

Regards

**Comment by abnerrizzi** [comment]
Well, I can't find anything about composer in docs, wiki in mreporting files, docs or wiki.

Could you help me with how to do that ?

**Comment by cedric-anne** [comment]
If you do not know how to use composer, just use the build archive: https://github.com/pluginsGLPI/mreporting/releases/download/1.6.1/glpi-mreporting-1.6.1.tar.bz2

**Comment by abnerrizzi** [comment]
Thanks for support, I ran composer install in the mreporting folder and **solved** my issue.

I hope uou should put that procedure onde README.md file of project.

Thanks for your effort.
