### ISSUE TITLE
Notifications mreporting

### ISSUE THREAD

**Issue by fire2418** [pluginsGLPI/mreporting#2]
Bonjour, 

J'ai remarqué des bugs avec les notifications de mreporting. Ci-joint l'erreur:
![erreur_mreporting](https://cloud.githubusercontent.com/assets/10270520/6779325/2c414760-d15b-11e4-8032-bfc565f34708.PNG)

Le compte utilisé est superutilisateur, j'ai vérifié il n'y a pas de soucis de droits sur mreporting, tous les rapports sont bien en "lecture".

Je me tiens à votre disposition si vous souhaitez plus d'informations sur ce bug.

**Comment by orthagh** [comment]
Pouvez vous nous fournir une copie d'une partie  de vos fichiers glpi/files/_logs/sql_errors.log et glpi/files/_logs/php_errors.log
Si possible seulement, les erreur en relations avec la capture fournie.

Merci d'avance.

**Comment by fire2418** [comment]
Je viens de refaire une tentative à l'instant, voici un lien Pastebin vers le log:
http://pastebin.com/DMC9f16P

**Comment by orthagh** [comment]
Pouvez vous m'indiquer à quels endroit vous arrivez à visualiser ces erreurs ?

**Comment by fire2418** [comment]
Je m'excuse, j'avais mal lu.
Le log concernait sql_errors.log.

Voici le pastebin pour le log php_errors.log:
http://pastebin.com/szEFsiTF

**Comment by orthagh** [comment]
Désolé d'insister :)

Pouvez-vous m'indiquer l'emplacement / le menu dans lequel vous constatez ces messages d'erreurs.

Merci d'avance

**Comment by fire2418** [comment]
Ah oui désolé :\
Donc pour avoir cette erreur, je vais dans les actions automatiques et j'execute l'action "Mreporting - SendNotifications".

Bizarrement, depuis que j'ai réinstallé le master actuel de mreporting, je n'ai plus les erreurs en mode debug. Les destinataires de la notification qui correspond à l'action automatique sont "Administrateur" et "Profil: Super-Admin"

Cela provoque l'ouverture de la fenêtre d'erreur en question. Dès que je sélectionne l'un des rapports qui s'affiche dans la liste déroulante, j'ai ensuite une erreur 404 "The requested URL /front/graph.php was not found on this server."

En effet, le fichier graph.php est présent dans le répertoire glpi/plugins/mreporting/front et non pas dans le répertoire glpi/front

**Comment by fire2418** [comment]
Bonjour, 

Le problème persiste avec la dernière version, 0.84+2.3.2, toujours avec les mêmes erreurs.
Je me tiens à votre disposition pour de plus amples renseignements.

**Comment by Gwenall-Photobox** [comment]
Bonjour, 

Je constate le même problème que fire2418.
Je remarqué que j'ai fait les mêmes étapes en tant que super-admin: 

1] - Dans le "Setup > Automatic action > SendNotifications", lorsque je clique sur le bouton "executer", la page contenant un menu déroulant s'affiche correctement. 
page:"http://server-glpi/front/crontask.form.php"
![screenshot from 2015-06-03 04 35 56](https://cloud.githubusercontent.com/assets/10615766/7952259/0caf2b46-09ab-11e5-9744-61ec4f86fb68.png)

![screenshot from 2015-06-03 04 41 54](https://cloud.githubusercontent.com/assets/10615766/7952297/b05a8bc8-09ab-11e5-9944-1f904586e109.png)

2] - Lorsque je choisi un des rapports du menu déroulant, la page "http://server-glpi/front/graph.php?...etc...etc" est appelée sans succès. 
Voici le message d'erreur : "Not Found", "The requested URL /front/graph.php was not found on this server." 
page: "http://server-glpi/front/graph.php?short_classname=Helpdesk&f_name=reportAreaNbTicket&gtype=area"
![screenshot from 2015-06-03 04 42 17](https://cloud.githubusercontent.com/assets/10615766/7952300/b6205e16-09ab-11e5-9649-a88a3eceb7b8.png)

J'ai également remarqué que le fichier graph.php est situé ici: /var/www/glpi/plugins/mreporting/front/graph.php
et que par conséquent, la page recherché n'est pas la bonne puisque l'url du point '2]' désigne un fichier qui n'existe pas: /var/www/glpi/front/graph.php 


GLPI 0.85.2
Mreporting 0.85+1.0-RC4

Merci d'avance, 
Je me tiens a votre disposition si vous souhaitez plus d'informations.

**Comment by Manu1400** [comment]
Des commits viennent d'être réalisés à ce propos par @orthagh : 
* https://github.com/pluginsGLPI/mreporting/commit/358ca11fff5e4921a7846d0505962bdc9defc8d3
* https://github.com/pluginsGLPI/mreporting/commit/982b8d113c625afb36085d1f9ade81467424af27

**Comment by Manu1400** [comment]
L'envoi par mail de *chaque* rapports fonctionne.

*Attention* : Cela n'utilise pas la queue (Fille d'attente des mails). Les mails partent immédiatement.
