### ISSUE TITLE
No report is available

### ISSUE THREAD

**Issue by Diegazo** [pluginsGLPI/mreporting#20]
When i go to the More reporting page and i try to add a report, I always see "No report is available!". In the right management option of reports, i put all in "reading" and i try pushing in "initialize graphics configuration", but it doesn't work. I have GLPI 0.85.5 and the plugin version is 0.90+1.0.

**Comment by orthagh** [comment]
Could you disconnect and reconnect for test ?

**Comment by Diegazo** [comment]
Yes. I restarted apache service but problem persists.

**Comment by fgendorf** [comment]
I'm using the same version of GLPI 0.85.5 and the same occurred here.

**Comment by Ruiseart** [comment]
I have the same problem in GLPI 0.90.

**Comment by fgendorf** [comment]
I found the problem, my language is en_US, the reports are only available in fr_FR

**Comment by orthagh** [comment]
Oh ! good point.
I'll check this week to have a fallback language (en_GB)

**Comment by fgendorf** [comment]
This change works for me:

function includeAdditionalLanguageFiles() {
    $language = isset($_SESSION["glpilanguage"]) ? $_SESSION["glpilanguage"] : 'fr_FR'; //Note : quick hack
    if (glob(GLPI_ROOT . "/plugins/mreporting/locales/reports_locales/*_$language.php")) {
        foreach (glob(GLPI_ROOT . "/plugins/mreporting/locales/reports_locales/*_$language.php") as $path) {
            include_once($path);
        }
    } else {
        foreach (glob(GLPI_ROOT . "/plugins/mreporting/locales/reports_locales/*_en_GB.php") as $path) {
            include_once($path);
        }
    }
}

**Comment by orthagh** [comment]
fixed by 67f8cf1a3da21207de4bef48c1ab493afa2c94b0

**Comment by fgendorf** [comment]
with your fix, if $_SESSION["glpilanguage"] language is pt_BR and doesn't exist any file *_pt_BR.php, the error will be the same.... I think you need put a default language if doesn't exist files

**Comment by neeftarah** [comment]
Hi,

Thank you for your help.

I have added a default language (English) and overwrite default translations by user's language ones if available (tabs by tabs in order to avoid problems with partial translations).

Fixes are in the commit : add8ce0 and will be added to next release.

Regards,
Jérémy
