### ISSUE TITLE
SQL error on upgrade to 0.90 version

### ISSUE THREAD

**Issue by tsmr** [pluginsGLPI/mreporting#22]
2015-10-07 15:02:40 [6@VS-GLPI01]
  *** MySQL query error:
  SQL: SELECT `profiles_id` 
      FROM `glpi_plugin_mreporting_profiles` 
      WHERE `reports` = READ 
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ' at line 3
  Backtrace :
  inc/dbmysql.class.php:803                          
  inc/dbmysql.class.php:536                          DBmysqlIterator->__construct()
  plugins/mreporting/inc/profile.class.php:157       DBmysql->request()
  plugins/mreporting/hook.php:141                    PluginMreportingProfile::getRight()
  inc/plugin.class.php:643                           plugin_mreporting_install()
  front/plugin.form.php:49                           Plugin->install()

**Comment by Manu1400** [comment]
Fix with  https://github.com/pluginsGLPI/mreporting/commit/ad7e33de08b1984c8e2cebfd3122596744854394
