### ISSUE TITLE
Reporting does not show HP Laptops

### ISSUE THREAD

**Issue by mskrishna20051974** [pluginsGLPI/mreporting#23]
Hi,

I installed your plugin on GLPI 0.85.2. However when u i generate reports, it does not show any HP laptops. I have attached few images for your reference.
Please help in fixing the same. 

![glpi-1](https://cloud.githubusercontent.com/assets/6532466/10363008/7b3cdb7a-6dcf-11e5-990e-2eb78c100bd4.PNG)
![glpi-2](https://cloud.githubusercontent.com/assets/6532466/10363007/7b3ad726-6dcf-11e5-831a-54d7a881c694.PNG)

**Comment by neeftarah** [comment]
Hi,

It should be fixed by 5728343 can you test it ?

Regards,
Jérémy

**Comment by mskrishna20051974** [comment]
Hi,

Thank you, it works now.

Best Regards,
Krishna M S
