### ISSUE TITLE
Datas export seems to be broken

### ISSUE THREAD

**Issue by neeftarah** [pluginsGLPI/mreporting#25]
Hi,

I test on the graph "Computer By OS" on GLPI 0.90 with MReporting 0.90-1.0.

__ODT Export :__
* An undesired line appear : "GLPI_URL/lib/Zend"
* the export "WITH DATAS" doesn't show the datas
* A template must be choose before export! Why ? What are theses different templates ? Can I customize them ? Why are they in the users preferences instead of in the graph export form ?

__CSV Export :__
* Work but presentation is different from GLPI interface

__PNG Export :__
* WORK

__SVG Export :__
* The svg file is broken. Can't open it. The code brackets in the file seems to be HTML encoded.

__No PDF Export :'(__

**Comment by neeftarah** [comment]
SVG Export fixed by 61e0bd1
But some graph doesn't have datas on SVG pictures.

**Comment by neeftarah** [comment]
ODT Export : the undesired line is removed by bc0ed50

**Comment by Manu1400** [comment]
> The svg file is broken. Can't open it. The code brackets in the file seems to be HTML encoded.

fixed with commits efcf4e01337dd7cf0e3bfe6d1e37c2309979a108 and 868e8f3f2f2fdf2738eeb056ebce88f12968b129
