### ISSUE TITLE
Incorrect number of tickets - Backlog graph

### ISSUE THREAD

**Issue by PascalGuinet** [pluginsGLPI/mreporting#27]
Hi,

When ticket_type is set to "incident" or "demande", ticket count is right.
When ticket_type is set to "tous", ticket count is the same as "incident".

Some debug infos : 
- POST VARIABLE 
type => -1

- SQL request 
244	SELECT DISTINCT DATE_FORMAT(date, '%y%m') as period, DATE_FORMAT(date, '%b %Y') as period_name, COUNT(DISTINCT glpi_tickets.id) as nb
FROM glpi_tickets
LEFT JOIN glpi_tickets_users tu ON tu.tickets_id = glpi_tickets.id AND tu.type = 2
LEFT JOIN glpi_groups_tickets gt ON gt.tickets_id = glpi_tickets.id AND gt.type = 2
LEFT JOIN glpi_groups_tickets gtr ON gtr.tickets_id = glpi_tickets.id AND gtr.type = 1
WHERE (glpi_tickets.date >= '2014-10-29 00:00:00' AND glpi_tickets.date <= ADDDATE('2015-10-29 00:00:00', INTERVAL 1 DAY) ) AND glpi_tickets.entities_id IN ('1') AND glpi_tickets.is_deleted = '0' AND glpi_tickets.type = 1 GROUP BY period
ORDER BY period

- Versions
GLPI 0.85.5 on FreeBSD 8.4 (issue too on SLE12)
Mreporting release from 2015-10-29

Regards

**Comment by Manu1400** [comment]
Corrigé sur mon repository : https://github.com/Manu1400/mreporting/commit/22fcb1c3e4e880687b0f4c28cb36ad77f33b8e53

Je sors prochainement cette nouvelle version de mreporting (qui intègre un gestionnaire de notification permettant de définir les filtres (critères) par cibles).
