### ISSUE TITLE
Soucis sur les profils

### ISSUE THREAD

**Issue by PierreTeclib** [pluginsGLPI/mreporting#32]
En installant directement la version 0.90-1.1 ( sans faire de mise à jour), il y un soucis sur la gestion des profils, je ne peux pas mettre les droits à d'autres profils que le Super Admin.
En passant par la mise à jour, j'ai encore une erreur sur un rapport:

 "reportHbarPrintersByStatus (Imprimantes par statut): " 

Erreur: PHP Notice: Undefined index: right in /var/www/html/glpi/plugins/mreporting/inc/profile.class.php at line 237

Erreur précédente:

2016-01-25 11:01:46 [2@srv-glpi]
  *** PHP Notice(8): Undefined offset: 30
  Backtrace :
  plugins/mreporting/inc/graphpng.class.php:1046     
  plugins/mreporting/inc/graphpng.class.php:975      PluginMreportingGraphpng->drawSunburstLevel()
  plugins/mreporting/inc/common.class.php:627        PluginMreportingGraphpng->showSunburst()
  plugins/mreporting/front/graph.php:38              PluginMreportingCommon->showGraph()

**Comment by orthagh** [comment]
Ca devrait être bon à l'installation avec 1bbe2949accf5f50d8662e624aeaebbe779b65c3

J'ai pas testé la maj, il faudra que tu me dises
