### ISSUE TITLE
Rapports impossible à afficher en SVG: reportSunburstTicketByCategories

### ISSUE THREAD

**Issue by PierreTeclib** [pluginsGLPI/mreporting#33]
reportSunburstTicketByCategories (Repartition des tickets par catégories et sous catégories): 

Affichage possible en PNG mais pas joli: 
![raaport_png](https://cloud.githubusercontent.com/assets/6872020/12548233/3d2a6f60-c355-11e5-9934-c3c8c216a107.png)

De plus une fois sur deux (apres deco/reco ou en changeant de profil ou même simplement en rafraichissant la page ) le graph s'affiche de cette façon: 
![raaport_png_error](https://cloud.githubusercontent.com/assets/6872020/12548250/5533f0c2-c355-11e5-8779-d7bf719ded17.png)

**Comment by orthagh** [comment]
2 commits pour améliorer la situation : 
4d6d5d322b99c67f916a608749cec31d50316df6
6f8f5f09d21c54b8395a9fe69269575fbc83ccd2

le master courant (https://github.com/pluginsGLPI/mreporting/archive/master.zip) les contient

**Comment by ropie** [comment]
Bien cordialement. 
Génial! 
Ca marche bien :) 





Pierre LEBEL 
Consultant Logiciel Libres 
Spécialiste GLPi 
plebel@teclib.com 

teclib' Caen - Bâtiment Olympus, 9 rue Léopold Sédar Senghor, 14460 Colombelles 
Tel. 01 85 09 00 61 - Std. +33 1 79 97 02 78 - Fax. +33 1 72 70 31 18 
Facebook | Twitter | www.teclib.com 

----- Mail original -----

De: "Alexandre Delaunay" <notifications@github.com> 
À: "pluginsGLPI/mreporting" <mreporting@noreply.github.com> 
Cc: "Pierre" <plebel@teclib.com> 
Envoyé: Lundi 25 Janvier 2016 12:00:23 
Objet: Re: [mreporting] Rapports impossible à afficher en SVG: reportSunburstTicketByCategories (#33) 



2 commits pour améliorer la situation : 
4d6d5d3 
6f8f5f0 


le master courant ( https://github.com/pluginsGLPI/mreporting/archive/master.zip ) les contient
