### ISSUE TITLE
graphs visualization problem

### ISSUE THREAD

**Issue by alibou66** [pluginsGLPI/mreporting#42]
I use à 0.90+1.1 version of mreporting on 0.90 GLPI Version and despite "init graph" i have a problem with graph vizualization 

I reinstalledà plugin and  nothing happens
can you help me 

Tks 
B/R

**Comment by flegastelois** [comment]
You can now use the latest version of the plugin (at this date **1.3.0 for GLPi 9.1**), which fixes this bug among others.
