### ISSUE TITLE
Uncaught TypeError: Argument 2 passed to Dropdown::showFromArray() must be of the type array, null given

### ISSUE THREAD

**Issue by Megachip** [pluginsGLPI/mreporting#46]
0.85.5:
```
PHP Notice: Undefined variable: datas in /var/www/html/glpi085/plugins/mreporting/inc/inventory.class.php at line 56

Fatal error: Uncaught TypeError: Argument 2 passed to Dropdown::showFromArray() must be of the type array, null given, called in /var/www/html/glpi085/plugins/mreporting/inc/inventory.class.php on line 56 and defined in /var/www/html/glpi085/inc/dropdown.class.php:1672 Stack trace: #0 /var/www/html/glpi085/plugins/mreporting/inc/inventory.class.php(56): Dropdown::showFromArray('states_id', NULL, Array) #1 /var/www/html/glpi085/plugins/mreporting/inc/inventory.class.php(33): PluginMreportingInventory::selectorForMultipleStates('states_id', '', 'State') #2 /var/www/html/glpi085/plugins/mreporting/inc/common.class.php(1586): PluginMreportingInventory::selectorMultipleStates() #3 /var/www/html/glpi085/plugins/mreporting/inc/common.class.php(1528): PluginMreportingCommon::getReportSelectors() #4 /var/www/html/glpi085/plugins/mreporting/inc/graph.class.php(82): PluginMreportingCommon::showSelector('2016-04-19', '2016-05-19', 'PluginMreportin...') #5 /var/www/html/glpi085/plugins/mreporting/inc/graph.class.php(151): PluginMrepor in /var/www/html/glpi085/inc/dropdown.class.php on line 1672
```

Same on glpi 0.90.3:
`2016-05-19 12:54:17 [7@hostname]
  *** PHP Notice(8): Undefined variable: datas
  Backtrace :
  plugins/mreporting/inc/inventory.class.php:56      
  plugins/mreporting/inc/inventory.class.php:33      PluginMreportingInventory::selectorForMultipleStates()
  plugins/mreporting/inc/common.class.php:1586       PluginMreportingInventory::selectorMultipleStates()
  plugins/mreporting/inc/common.class.php:1528       PluginMreportingCommon::getReportSelectors()
  plugins/mreporting/inc/graph.class.php:82          PluginMreportingCommon::showSelector()
  plugins/mreporting/inc/graph.class.php:343         PluginMreportingGraph->initGraph()
  plugins/mreporting/inc/common.class.php:627        PluginMreportingGraph->showPie()
  plugins/mreporting/front/graph.php:38              PluginMreportingCommon->showGraph()`

**Comment by flegastelois** [comment]
Hi,
Which version of the plugin do you use?
What actions did you do for this error?
Regards,
