### ISSUE TITLE
Graphs are shown to unathenticated users

### ISSUE THREAD

**Issue by sebelk** [pluginsGLPI/mreporting#53]
Hi! I've found that is possible access to graphics being non-authenticated.... is it a bug?

For example https://www.example.com/plugins/mreporting/front/graph.php?short_classname=Helpdesk&f_name=reportPieTicketOpenedAndClosed&gtype=pie

My version of GLPI is 0.90.1

Thanks in advance

**Comment by trasher** [comment]
I confirm the issue. Menus and dashboard pages are protected according to the plugin ACLs configuration, but the report itself stay visible entering direct URL

**Comment by trasher** [comment]
Small precision: I can reproduce the issue with a logged in user without ACLs, but not for not authenticated users.

**Comment by sebelk** [comment]
I've checked again: a not authenticated user can access to reports unless  I create an .htaccess file  :(
