### ISSUE TITLE
Not sending notifications

### ISSUE THREAD

**Issue by sebelk** [pluginsGLPI/mreporting#54]
I use GLPI  0.90.1

I've installed commit 3f70b842ce8d5c1312a5c39b885c77d2cfbab74 of mreporting

When I go to Setup>Automatic Actions>SendNotifications and I clic on Execute it goes to https://my.example.com/front/crontask.form.php and does nothing,

On logs I've found:

> 
[Fri Aug 26 11:23:16.867038 2016] [:error] [pid 9095] [client 192.168.22.37:34254] PHP Fatal error:  Call to a member function fetch_assoc() on a non-object in /var/www/html/inc/dbmysql.class.php on line 280, referer: https://my.example.com/front/crontask.form.php?id=41

Please could you help me?

Thanks in advance!

**Comment by sebfun** [comment]
You should activate debug bug on super admin user's preference and retry. That should give you more informations

**Comment by flegastelois** [comment]
Hi,
Typically **PHP Fatal error** on **dbmysql.class** indicates that there is a sql error.
See "sql-errors.log" instead of "php-errors.log".
