### ISSUE TITLE
Bad comparaison in Nb tickets per SLA

### ISSUE THREAD

**Issue by awslgr** [pluginsGLPI/mreporting#56]
To determine if a ticket is respected or not, as compared with the SLA resolution time, the query is like that : 
`SELECT DISTINCT
            DATE_FORMAT(`date`, '%y%m') AS period,
            DATE_FORMAT(`date`, '%b %Y') AS period_name,
            count(glpi_tickets.id) AS nb,
            s.name,
            CASE WHEN solve_delay_stat <= s.resolution_time THEN 'ok' ELSE 'nok' END AS respected_sla
         FROM`glpi_tickets`
         INNER JOIN`glpi_slas`s
            ON slas_id = s.id
         WHERE (glpi_tickets.date >= '2015-09-08 00:00:00' AND glpi_tickets.date <= ADDDATE('2016-09-07 00:00:00', INTERVAL 1 DAY) )
         AND status IN (5,17,18,6)
         AND glpi_tickets.entities_id IN ('0', '2541')
         AND glpi_tickets.is_deleted = '0' AND s.id IN (3) GROUP BY s.name, period, respected_sla`

As we can see, there is a comparaison between glpi_tickets.resolve_delay_stat (number of seconds), and glpi_slas.resolution_time. resolution_time depends on definition_time (day, hour, minute), so it can't work.

The solution could be to change the query like that : 
`
CASE 
  WHEN definition_time = 'day' and solve_delay_stat <= s.resolution_time * 3600 * 24 THEN 'ok' 
  WHEN definition_time = 'hour' and solve_delay_stat <= s.resolution_time * 3600 THEN 'ok' 
  WHEN definition_time = 'minute' and solve_delay_stat <= s.resolution_time * 60 THEN 'ok' 
  ELSE 'nok'
END AS respected_sla
`

Am i right ?
Thanks a lot

**Comment by flegastelois** [comment]
I confirm.
