### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Bullot78** [pluginsGLPI/mreporting#60]
Hello,
when trying to update the plugin, getting following error:

Parse error: syntax error, unexpected '.', expecting ',' or ';' in /var/www/glpi/plugins/mreporting/inc/helpdeskplus.class.php on line 12

Same issue on a fresh install.

Tested with glpi 0.90.1 and glpi 0.91.

Best Regards

**Comment by btry** [comment]
Hi

Can you tell the version if the plugin you're using ?

**Comment by Bullot78** [comment]
Sorry, not used of Git. Still installing from tar.gz.

Solved in the last file of git repository but not in tar.gz.

Plugin version: glpi-mreporting-0.90-1.2.tar.gz

Thank you for this great plugin

**Comment by btry** [comment]
Thank you for your report.

If using the latest revision solved the issue, can we close it ?

**Comment by Bullot78** [comment]
Yes using the tar file and replacing the file helpdeskplus.class.php with the latest one from git worked for me on my production version in 0.90.1.
Not yet tested with 0.91.

Thank You

**Comment by btry** [comment]
FYI you may download the very latest revision with the green button on the home page https://github.com/pluginsGLPI/mreporting

This would be a bit safer than picking a single file.

**Comment by Bullot78** [comment]
Tried,  but latest 0.90+1.1 and not compatible with my glpi 0.90.1 :(

**Comment by Moiwouam** [comment]
Hi there,

I think you should re-open this issue as I have the same problem as Bullot78.

I'm using GLPI 0.90.5 so I downloaded mreporting [0.90+1.2](https://github.com/pluginsGLPI/mreporting/releases/download/0.90%2B1.2/glpi-mreporting-0.90-1.2.tar.gz).
Then I cannot install it, same error message "helpdeskplus.class.php on line 12".
So I downloaded only the file "helpdeskplus.class.php" from the release [1.3.0](https://github.com/pluginsGLPI/mreporting/releases/download/1.3.0/glpi-mreporting-1.3.0.tar.gz) to replace it, despite the 1.3.0 is for GLPI >= 9.1
Then the installation completed successfully and I can enable and use the mreporting.

This is clearly not a recommended solution but in my case it works...
