### ISSUE TITLE
problème de mise à jour depuis mreporting 0.90+1.0

### ISSUE THREAD

**Issue by sebfun** [pluginsGLPI/mreporting#65]
Bonjour
Une fois que j'ai copié tous les fichiers nécessaire à la mise à jour. Quand je fais Mettre à jour le plugin depuis la gestion des plugins cela indique "Traitement en cours..." mais il ne se passe rien. Pas de charge sur le serveur, pas de mise à jour. J'ai laissé tourner pendant 2h cela n'a rien donné.
J'ai bien GLPI 9.1 installé correctement. Tous les autres plugins sont désactivés.
Merci d'avance

**Comment by bacus99** [comment]
Si tu active ton debug mode?  Tu as des erreurs?

Date: Tue, 18 Oct 2016 05:50:21 -0700

**Comment by sebfun** [comment]
effectivement 


Traitement en cours...

Parse error: syntax error, unexpected '-', expecting '{' in D:\xampp\htdocs\glpi\plugins\mreporting\inc\ordi-fournisseur.class.php on line 4

La ligne 4 correspond à 
class PluginMreportingordi-fournisseur Extends PluginMreportingBaseclass {

**Comment by sebfun** [comment]
Je crois que je viens de comprendre 
En fait c'est une class que j'avais commencé pour créer un graphique personnalisé. Je ne l'avais pas fini.
Je viens de voir que ce fichier n'existe pas dans le package .tar.gz.
Je viens de tester cela fonctionne parfaitement. La mise à jour s'est correctement déroulée. 
Désolé pour le dérangement, je clos.
