### ISSUE TITLE
Gabarits pris à tord dans les restitutions

### ISSUE THREAD

**Issue by johannsan** [pluginsGLPI/mreporting#73]
Bonjour.

Dans la requête "Inventaire/Répartition du nombre d'ordinateurs par entités", les gabarits sont pris à tord car : 
- la requête ressort 6 ordinateurs
- j'ai 4 ordinateurs et deux gabarits.

J'ai donc peur que cela soit le cas sur l'ensemble des requêtes.

Cdt.

**Comment by flegastelois** [comment]
Bonjour,

Ce n'est que dans la graphique par entité, les autres filtrent bien les "delete" et les "templates".

J'indique que c'est un bug pour correctif.
