### ISSUE TITLE
Remove require "GLPI_PHPMAILER_DIR"

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/mreporting#74]
`Fatal error: require_once(): Failed opening required 'GLPI_PHPMAILER_DIR/class.phpmailer.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/public/plugins/mreporting/inc/notificationmail.class.php on line 7`

**Comment by trasher** [comment]
Include should just be dropped; GLPi's autoloader should be active and do its job
