### ISSUE TITLE
problème de sélection de plusieurs graph

### ISSUE THREAD

**Issue by sebfun** [pluginsGLPI/mreporting#77]
Bonjour

Quand je veux choisir des graphs dans GLPI 9.1 et Mreporting 1.3.0 sur la page d'accueil du tableau de bord j'ai cette erreur en mode debug

`Fatal error: Call to a member function fetch_assoc() on a non-object in D:\xampp\htdocs\glpi\inc\dbmysql.class.php on line 308`

Mes graphs ne s'affichent pas

Lorsque je clique sur le bouton Ajouter j'obtiens la même erreur

Si je fais "sélectionner un rapport à afficher" il me l'affiche bien.
Si je reviens sur la page d'accueil du plugin, il a disparu et l'erreur précédente est apparue

Merci d'avance

**Comment by flegastelois** [comment]
Bonjour,

Quand bien même le plugin vous autorise à ajouter deux fois le même graphique sur le dashboard, le code n'est pas prévu pour le gérer : cette fonctionnalité va très certainement être développée dans une prochaine version.

Par contre, une erreur PHP **Fatal error: Call to a member function fetch_assoc()** dans la classe **dbmysql.class.php** veut dire que vous avez une erreur SQL : pouvez-vous regarder dans le fichier **glpi/files/_log/sql-errors.php** ?

**Comment by sebfun** [comment]
Bonjour
Je n'ai pas dit que je voulais ajouter 2x le même graph j'ai indiqué que je voulais ajouter plusieurs graphiques comme dans la version précédente ce qui était bien pratique pour avoir une vue d'ensemble sur les tickets en cours, l'âge du matériel, etc... J'avais mis 6 graphiques différents cela passait sans problème

` *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt
             FROM `glpi_computers` WHERE `operatingsystems_id` IN (2)
                                            AND `is_deleted`=0
                                            AND `is_template`=0
                                             AND entities_id IN (\'0\', \'7\', \'2\', \'6\', \'5\', \'1\', \'4\', \'3\')
                                             AND c.states_id IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14) 
  Error: Unknown column 'c.states_id' in 'where clause'
  Backtrace :
  inc\db.function.php:319                            
  plugins\mreporting\inc\inventory.class.php:408     countElementsInTable()
  plugins\mreporting\inc\common.class.php:608        PluginMreportingInventory->reportHbarWindows()
  plugins\mreporting\inc\dashboard.class.php:191     PluginMreportingCommon->showGraph()
  plugins\mreporting\front\dashboard.form.php:36     PluginMreportingDashboard->showDashBoard()
  plugins\mreporting\front\dashboard.php:2           require_once()`

**Comment by sebfun** [comment]
J'ai trouvé 2 autres erreurs :

**Comment by flegastelois** [comment]
Bonjour,

My mistake, j'avais lu trop vite votre premier message :)
Je confirme le bug de mon côté également : j'ai ajouté le label "bug" pour effectuer un fix.

Merci pour votre retour,

**Comment by sebfun** [comment]
pas de problème :) 
merci à vous
