### ISSUE TITLE
Notice PHP7 : A non well formed numeric value encountered

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/mreporting#79]
> 2016-11-18 09:55:55 [2182@glados]
  *** PHP Notice(8): A non well formed numeric value encountered
  Backtrace :
  :                                                  
  ...orting/lib/imagesmootharc/imageSmoothArc.php:45 imagecolorexactalpha()
  ...rting/lib/imagesmootharc/imageSmoothArc.php:337 imageSmoothArcDrawSegment()
  plugins/mreporting/inc/graphpng.class.php:1887     imageSmoothArc()
  plugins/mreporting/inc/common.class.php:623        PluginMreportingGraphpng->showArea()
  ...inc/notificationtargetnotification.class.php:89 PluginMreportingCommon->showGraph()
  ...inc/notificationtargetnotification.class.php:22 PluginMreportingNotificationTargetNotification->_buildPDF()
  inc/notificationtarget.class.php:1072              PluginMreportingNotificationTargetNotification->getDatasForTemplate()
  inc/notificationtemplate.class.php:243             NotificationTarget->getForTemplate()
  ...s/mreporting/inc/notificationevent.class.php:72 NotificationTemplate->getTemplateByLanguage()
  plugins/mreporting/inc/notification.class.php:145  PluginMreportingNotificationEvent::raiseEvent()
  inc/crontask.class.php:834                         PluginMreportingNotification::cronSendNotifications()
  front/crontask.form.php:50                         CronTask::launch()

> 2016-11-18 09:55:55 [2182@glados]
  *** PHP Notice(8): A non well formed numeric value encountered
  Backtrace :
  :                                                  
  plugins/mreporting/inc/graphpng.class.php:1894     imagettftext()
  plugins/mreporting/inc/common.class.php:623        PluginMreportingGraphpng->showArea()
  ...inc/notificationtargetnotification.class.php:89 PluginMreportingCommon->showGraph()
  ...inc/notificationtargetnotification.class.php:22 PluginMreportingNotificationTargetNotification->_buildPDF()
  inc/notificationtarget.class.php:1072              PluginMreportingNotificationTargetNotification->getDatasForTemplate()
  inc/notificationtemplate.class.php:243             NotificationTarget->getForTemplate()
  ...s/mreporting/inc/notificationevent.class.php:72 NotificationTemplate->getTemplateByLanguage()
  plugins/mreporting/inc/notification.class.php:145  PluginMreportingNotificationEvent::raiseEvent()
  inc/crontask.class.php:834                         PluginMreportingNotification::cronSendNotifications()
  front/crontask.form.php:50                         CronTask::launch()

> 2016-11-18 09:55:55 [2182@glados]
  *** PHP Notice(8): A non well formed numeric value encountered
  Backtrace :
  :                                                  
  plugins/mreporting/inc/graphpng.class.php:1899     imageline()
  plugins/mreporting/inc/common.class.php:623        PluginMreportingGraphpng->showArea()
  ...inc/notificationtargetnotification.class.php:89 PluginMreportingCommon->showGraph()
  ...inc/notificationtargetnotification.class.php:22 PluginMreportingNotificationTargetNotification->_buildPDF()
  inc/notificationtarget.class.php:1072              PluginMreportingNotificationTargetNotification->getDatasForTemplate()
  inc/notificationtemplate.class.php:243             NotificationTarget->getForTemplate()
  ...s/mreporting/inc/notificationevent.class.php:72 NotificationTemplate->getTemplateByLanguage()
  plugins/mreporting/inc/notification.class.php:145  PluginMreportingNotificationEvent::raiseEvent()
  inc/crontask.class.php:834                         PluginMreportingNotification::cronSendNotifications()
  front/crontask.form.php:50                         CronTask::launch()

**Comment by trasher** [comment]
Should have been fixed in develop.
