### ISSUE TITLE
Update core plugin locales from/to Transifex

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/mreporting#85]
https://www.transifex.com/teclib/glpi-project-plugin-mreporting/

**Comment by AircraftRu** [comment]
Please tell me when will be translated?

**Comment by AircraftRu** [comment]
Hello, why nobody does not solved the issue?

**Comment by btry** [comment]
Hi 

Updating the locales should be done in the release process.

However you may download the sources, add missing strings if any, and build the locales if you really cannot wait for the next release.

**Comment by AircraftRu** [comment]
Hi,
I translated all long ago but many word not exist on [Transifex](https://www.transifex.com/teclib/glpi-project-plugin-mreporting/), example #88

> However you may download the sources, add missing strings if any, and build the locales if you really cannot wait for the next release.
Ok, I got it. I will try. Thank you! =)
