### ISSUE TITLE
Install Error  (mreporting 0.90+1.2 on GLPI 0.90.5)

### ISSUE THREAD

**Issue by LordBat** [pluginsGLPI/mreporting#87]
Hi, when i try to install the plugin i have this error.

Changing the database layout - glpi_plugin_mreporting_preferences

Parse error: syntax error, unexpected '.', expecting ',' or ';' in /var/www/html/glpi/plugins/mreporting/inc/helpdeskplus.class.php on line 12

Regards!

**Comment by bacus99** [comment]
Delete the file and everything works.


________________________________
De : LordBat <notifications@github.com>
Envoyé : 21 novembre 2016 09:13
À : pluginsGLPI/mreporting
Objet : [pluginsGLPI/mreporting] Install Error (mreporting 0.90+1.2 on GLPI 0.90.5) (#87)


Hi, when i try to install the plugin i have this error.

Changing the database layout - glpi_plugin_mreporting_preferences

Parse error: syntax error, unexpected '.', expecting ',' or ';' in /var/www/html/glpi/plugins/mreporting/inc/helpdeskplus.class.php on line 12

Regards!

-

**Comment by LordBat** [comment]
Thanks!!! now works!

**Comment by trasher** [comment]
I guess trying to fix would be better than remove completely the file.

Something like this should do the tricl:
```
diff --git a/inc/helpdeskplus.class.php b/inc/helpdeskplus.class.php
index bbf6873..d4fea3d 100644
--- a/inc/helpdeskplus.class.php
+++ b/inc/helpdeskplus.class.php
@@ -9,7 +9,7 @@ class PluginMreportingHelpdeskplus Extends PluginMreportingBaseclass {
    protected $sql_group_assign  = "1=1",
              $sql_group_request = "1=1",
              $sql_user_assign   = "1=1",
-             $sql_type          = "glpi_tickets.type IN (".Ticket::INCIDENT_TYPE.", ".Ticket::DEMAND_TYPE.")",
+             $sql_type,
              $sql_itilcat       = "1=1",
 
              $sql_join_cat      = "LEFT JOIN glpi_itilcategories cat
@@ -36,6 +36,7 @@ class PluginMreportingHelpdeskplus Extends PluginMreportingBaseclass {
 
       parent::__construct($config);
 
+      $this->sql_type  = "glpi_tickets.type IN (".Ticket::INCIDENT_TYPE.", ".Ticket::DEMAND_TYPE.")";
       $this->lcl_slaok = $LANG['plugin_mreporting']['Helpdeskplus']['slaobserved'];
       $this->lcl_slako = $LANG['plugin_mreporting']['Helpdeskplus']['slanotobserved'];
```
