### ISSUE TITLE
Many words are not translated

### ISSUE THREAD

**Issue by AircraftRu** [pluginsGLPI/mreporting#88]
Many words are not translated, although all translated transifeks.
mreporting 1.3.1
GLPI 9.1.1

![mreporting](https://cloud.githubusercontent.com/assets/17082164/20865793/ec12f3f2-ba2c-11e6-982b-0425b7fe736d.png)

![mreporting1](https://cloud.githubusercontent.com/assets/17082164/20865800/fd8845a6-ba2c-11e6-98f6-7545502e7c4d.png)

**Comment by flegastelois** [comment]
See #85
