### ISSUE TITLE
Menu manquant dans Outils (plugin version 1.3.1)

### ISSUE THREAD

**Issue by sebfun** [pluginsGLPI/mreporting#91]
Bonjour

dans la version 1.3.1 pour GLPI 9.1.1 pour des profils déjà créés, lorsque je mets des droits de lecture sur des graphiques à un profil autre que super admin, le menu Plus de rapports n'apparaît pas dans le menu Outils du coup, impossible pour l'utilisateur d'accéder aux graphiques.

J'ai remarqué dans la base de données dans la table mreporting_profiles le champ reports va jusqu'à la valeur 48 pour le profil super admin alors que pour les profils créés en plus il va jusqu'à 51

Faut-il que je fasse initialiser la configuration des graphiques ?

**Comment by sebfun** [comment]
Bonjour
Alors pour les erreurs j'ai ceci : 
`` *** PHP Notice(8): Undefined index: mreporting_values
  Backtrace :
  plugins\mreporting\inc\helpdeskplus.class.php:65   
  plugins\mreporting\inc\config.class.php:537        PluginMreportingHelpdeskplus->__construct()
  inc\commondbtm.class.php:1065                      PluginMreportingConfig->prepareInputForUpdate()
  plugins\mreporting\front\config.form.php:44        CommonDBTM->update()``

Pour les graphiques il s'agit de ceux concernant le support (ils sont bien marqués sur "Lecture") : 
reportPieTicketNumberByEntity (Nombre de ticket par entités): 	
reportHbarTicketNumberByEntity (Nombre de ticket par entités): 	
reportHgbarTicketNumberByCatAndEntity (Nombre de ticket par catégories et entités): 	
reportPieTicketOpenedAndClosed (Nombre de tickets ouverts et clôturés): 	
reportPieTicketOpenedbyStatus (Nombre de tickets ouverts par statuts): 	
reportPieTopTenAuthor (Top 10 des demandeurs): 	
reportHgbarOpenTicketNumberByCategoryAndByType (Nombre de tickets ouverts par catégories et par types): 	
reportHgbarCloseTicketNumberByCategoryAndByType (Nombre de tickets clôturés par catégories et par types): 	
reportHgbarTicketNumberByService (Nombre de tickets ouverts et clôturés par services): 	
reportHgbarOpenedTicketNumberByCategory (Nombre de tickets ouverts par catégories et par statuts): 	
reportLineNbTicket (Evolution du nombre de ticket sur la période): 	
reportAreaNbTicket (Evolution du nombre de ticket sur la période): 	
reportVstackbarNbTicket (Evolution du nombre de ticket sur la période (par Statut)): 	
reportGareaNbTicket (Evolution du nombre de ticket sur la période (par Statut)): 	
reportGlineNbTicket (Evolution du nombre de ticket sur la période (par Statut)): 	
reportSunburstTicketByCategories (Repartition des tickets par catégories et sous catégories): 	
reportVstackbarTicketStatusByTechnician (Nombre de tickets par statuts et technicien): 	
reportHbarTicketNumberByLocation (Nombre de ticket par lieu des demandeurs): 	
reportGlineBacklogs (Backlog): 	
reportVstackbarLifetime (Ancienneté des tickets): 	
reportVstackbarTicketsgroups (Quantitatif par groupes): 	
reportVstackbarTicketstech (Quantitatif par technicien): 	
reportHbarTopcategory (TOP catégories): 	
reportHbarTopapplicant (TOP groupes demandeurs): 	
reportVstackbarGroupChange (Nombre de changement de groupe): 	
reportGlineNbTicketBySla (Evolution du nombre de tickets par SLA): 	
reportHgbarRespectedSlasByTopCategory (Nombre de tickets par SLA ordonnés par catégories): 	
reportHgbarRespectedSlasByTechnician (Nombre de tickets par SLA ordonnées par techniciens): 	
reportVstackbarRespectedSlasByGroup (Nombre de tickets par SLA ordonnés par groupes): 	
reportVstackbarNbTicketBySla (Nombre de tickets par SLA): 

Merci d'avance de votre aide

**Comment by Alkashee** [comment]
Bonjour,

J'ai exactement le même problème. Il n'y a que le profil super-admin qui a les droits de lecture des rapports. Quand je veux les changer pour les autres profils, rien ne change. A tout hasard j'ai testé avec le compte glpi (le root en somme) et même résultat. Y-a-t-il une façon spécifique de faire ?

**Comment by Alkashee** [comment]
Bonjour,

Petit up de la question précédente :)

**Comment by Alkashee** [comment]
Pas de nouvelles ? :(

**Comment by amma35** [comment]
Bonjour,

L'affichage du menu dans "Outils" se fait en fonction du droit Lecture de Statistiques.

**Comment by sebfun** [comment]
merci je clos cette demande
